Process-1 | log time - 2022-08-03 13:44:11 | log level - INFO | [main.py: line - 381 in function checkNumAds] | Формирование очереди ссылок
Process-1 | log time - 2022-08-03 13:44:11 | log level - INFO | [main.py: line - 36 in function startBrowser] | Применения прокси 192.168.0.85:3289 для запуска браузера
Process-1 | log time - 2022-08-03 13:44:57 | log level - WARNING | [connectionpool.py: line - 780 in function urlopen] | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000005F13250>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение')': /session/c2ed56edb0b01d99b882b4e0b2865173/window
Process-1 | log time - 2022-08-03 13:44:59 | log level - WARNING | [connectionpool.py: line - 780 in function urlopen] | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000005F09A00>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение')': /session/c2ed56edb0b01d99b882b4e0b2865173/window
Process-1 | log time - 2022-08-03 13:45:01 | log level - WARNING | [connectionpool.py: line - 780 in function urlopen] | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000643E4C0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение')': /session/c2ed56edb0b01d99b882b4e0b2865173/window
Process-1 | log time - 2022-08-03 13:45:03 | log level - INFO | [main.py: line - 36 in function startBrowser] | Применения прокси 192.168.0.85:3289 для запуска браузера
Process-1 | log time - 2022-08-03 13:45:05 | log level - INFO | [main.py: line - 272 in function ads_data] | Начало проверки объявлений
Process-1 | log time - 2022-08-03 13:45:05 | log level - INFO | [main.py: line - 280 in function ads_data] | Проверка объявления https://avito.ru/yoshkar-ola/zemelnye_uchastki/uchastok_12sot._izhs_2403046699
